In [91]:
import numpy as np
import pandas as pd
import seaborn as sns
import warnings as wn
import matplotlib as plt


pd.set_option('mode.chained_assignment',None)
pd.set_option('display.max_colwidth', -1)
pd.options.display.max_columns = 50
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')
%matplotlib inline

In [92]:
dir_path = "C:/Users/vik2nu/Desktop/AI_ML/Term1_2_Project/01_Startup_Data/"
sfin=pd.read_csv(dir_path+'startup_funding.csv')
sfin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
Sr No                3044 non-null int64
Date dd/mm/yyyy      3044 non-null object
Startup Name         3044 non-null object
Industry Vertical    2873 non-null object
SubVertical          2108 non-null object
City  Location       2864 non-null object
Investors Name       3020 non-null object
InvestmentnType      3040 non-null object
Amount in USD        2084 non-null object
Remarks              419 non-null object
dtypes: int64(1), object(9)
memory usage: 237.9+ KB

In [93]:
sfin.tail(10)

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
3034,3035,24/01/2015,Aasaanjobs,NaN,NaN,NaN,"Inventus Capital Partners, IDG Ventures",Seed Funding,"15,00,000",NaN
3035,3036,24/01/2015,Impartus,NaN,NaN,NaN,Kaizen Private Equity,Private Equity,NaN,Series A
3036,3037,25/01/2015,Thrill App,NaN,NaN,NaN,People Group (Shaadi.com),Private Equity,"10,00,000",Strategic Funding
3037,3038,27/01/2015,CarDekho.com,NaN,NaN,NaN,"Hillhouse Capital, Tybourne Capital",Private Equity,"5,00,00,000",Series B
3038,3039,28/01/2015,Grabhouse.com,NaN,NaN,NaN,"Kalaari Capital, Sequoia Capital",Private Equity,"25,00,000",Series A
3039,3040,29/01/2015,Printvenue,NaN,NaN,NaN,Asia Pacific Internet Group,Private Equity,"45,00,000",NaN
3040,3041,29/01/2015,Graphene,NaN,NaN,NaN,KARSEMVEN Fund,Private Equity,"8,25,000",Govt backed VC Fund
3041,3042,30/01/2015,Mad Street Den,NaN,NaN,NaN,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",NaN
3042,3043,30/01/2015,Simplotel,NaN,NaN,NaN,MakeMyTrip,Private Equity,NaN,"Strategic Funding, Minority stake"
3043,3044,31/01/2015,couponmachine.in,NaN,NaN,NaN,UK based Group of Angel Investors,Seed Funding,"1,40,000",NaN

In [94]:
sfin['Startup Name'].value_counts()

Swiggy                     8
Ola Cabs                   8
Paytm                      7
UrbanClap                  6
Medinfi                    6
Meesho                     6
Nykaa                      6
NoBroker                   6
Capital Float              5
Moglix                     5
Flipkart                   5
Grofers                    5
Toppr                      5
Uniphore                   5
Jugnoo                     5
Ola                        4
RailYatri                  4
Zoctr                      4
Byju\\xe2\\x80\\x99s       4
Fynd                       4
Magicpin                   4
BigBasket                  4
Niki.ai                    4
Zomato                     4
Udaan                      4
Icertis                    4
Healthians                 4
Simplilearn                4
Rivigo                     4
HealthifyMe                4
                          ..
ORIGA Leasing              1
MyDentistChoice            1
Leadburg                   1
MyCuteOffice               1
Quifers                    1
Carcrew.in                 1
TapChief                   1
Digital Gorkha             1
Augrav                     1
FiTraQ                     1
FleetX                     1
La Renon                   1
Specsmakers                1
Fashionove                 1
pi Ventures                1
The Good Life              1
Gridle                     1
Bank Bazaar                1
Orahi                      1
IntelligenceNODE           1
SmartCoin                  1
Bueno                      1
Appario Retail Pvt Ltd.    1
zippserv                   1
Bumper                     1
inclov                     1
Appvigil                   1
1mg (Healthkartplus)       1
Arcatron                   1
Locanix                    1
Name: Startup Name, Length: 2459, dtype: int64

In [95]:
sfin['Industry Vertical'].value_counts()

Consumer Internet                            941
Technology                                   478
eCommerce                                    186
Healthcare                                   70
Finance                                      62
ECommerce                                    61
Logistics                                    32
E-Commerce                                   29
Education                                    24
Food & Beverage                              23
Ed-Tech                                      14
E-commerce                                   12
FinTech                                      9
Ecommerce                                    8
IT                                           8
Fin-Tech                                     6
Real Estate                                  6
Food and Beverage                            6
Others                                       6
Online Food Delivery                         5
Health and Wellness                          5
Online Education Platform                    5
Logistics Tech                               5
Transport                                    4
Transportation                               4
Hyperlocal Handyman Services                 3
Information Technology                       3
Food Delivery Platform                       3
Big Data & Analytics platform                3
FMCG                                         3
                                            ..
Online Travel Marketplace                    1
Hyper local logistics platform               1
Bike Rental Platform                         1
Gourmet Meals Delivery                       1
Tech enabled logistics platform              1
Ecommerce Product recommendation platform    1
Hyperlocal Logistics Service                 1
B2B-focused foodtech startup                 1
Data Driven recruitment recommendation       1
Virtual Health consultation app              1
\\xc2\\xa0Online Grocery Delivery            1
visual search and discovery platform         1
Hyper-local Online Services                  1
Indian Ethnic Crafts Etailer                 1
Ecommerce Logistics                          1
Credit Card Fraud protection solutions       1
hyperlocal online Services platform          1
Parents focused Web Content                  1
Crowd Funding Platform                       1
Language Learning App                        1
360-degree view creating platform            1
Healthy Meals Food delivery platform         1
Electronic Goods recycling service           1
Product Discovery & comparison App           1
Beauty and Wellness Marketplace              1
Accounting                                   1
Social Network for Artists                   1
Career Development                           1
Hyperlocal grocery delivery                  1
Enterprise Communication Platform            1
Name: Industry Vertical, Length: 821, dtype: int64

In [96]:
sfin['InvestmentnType'].value_counts()

Private Equity                 1356
Seed Funding                   1355
Seed/ Angel Funding            60
Seed / Angel Funding           47
Seed\\nFunding                 30
Debt Funding                   25
Series A                       24
Seed/Angel Funding             23
Series B                       20
Series C                       14
Series D                       12
Angel / Seed Funding           8
Seed Round                     7
Pre-Series A                   4
Private Equity Round           4
Seed                           4
Seed / Angle Funding           3
Venture Round                  2
Corporate Round                2
pre-Series A                   2
Series E                       2
Series F                       2
Equity                         2
Funding Round                  1
Seed funding                   1
Inhouse Funding                1
Pre Series A                   1
Crowd Funding                  1
Bridge Round                   1
Structured Debt                1
Term Loan                      1
pre-series A                   1
Debt                           1
Private Funding                1
Crowd funding                  1
Series B (Extension)           1
Series J                       1
Single Venture                 1
Maiden Round                   1
Seed Funding Round             1
Venture - Series Unknown       1
PrivateEquity                  1
Series G                       1
Debt-Funding                   1
Angel Funding                  1
Venture                        1
Mezzanine                      1
Series H                       1
Private                        1
Angel                          1
Private\\nEquity               1
Angel Round                    1
Debt and Preference capital    1
Equity Based Funding           1
Pre-series A                   1
Name: InvestmentnType, dtype: int64

In [97]:
sfin['SubVertical'].value_counts()

Online Lending Platform                                                       11
Online Pharmacy                                                               10
Food Delivery Platform                                                        8
Online lending platform                                                       5
Online Lending                                                                5
Education                                                                     5
Online Education Platform                                                     5
Online Learning Platform                                                      5
Online Food Delivery                                                          4
Non-Banking Financial Company                                                 4
Agri-tech                                                                     3
Online Payment Gateway                                                        3
Logistics                                                                     3
Online platform for Higher Education Services                                 3
SaaS                                                                          3
Online Marketplace                                                            3
Online learning platform                                                      3
Data Analytics platform                                                       3
Online Food Delivery Platform                                                 3
B2B Marketplace                                                               3
Online Insurance Aggregator                                                   3
ECommerce Marketplace                                                         3
Online Insurance Platform                                                     3
Online Gifting platform                                                       3
E-learning                                                                    3
Online Furniture Store                                                        3
Fitness Mobile App                                                            3
Micro Lending Platform                                                        2
B2B Logistics provider                                                        2
Artificial Intelligence                                                       2
                                                                             ..
Edutainment platform                                                          1
Train PNR Status Prediction Platform                                          1
Goods & Services Barter Platform                                              1
Social gaming platform                                                        1
WiFi Analytics Platform                                                       1
Beauty Salon Aggregator                                                       1
Personalisation Technology Firm Focusing On The Food And Beverage Industry    1
Art                                                                           1
Lending Platform For Micro and Small Enterprises                              1
Mobile games developer                                                        1
Customer Success Software for B2B SaaS                                        1
Energy Analytics startup                                                      1
Wine                                                                          1
Personal Finance Mobile App                                                   1
Online Branded Budget Room Booking Service                                    1
Online Test Preparation platform                                              1
Patient Financing Platform                                                    1
Online fresh fruits and grocery store                                         1
Bike Taxi Service & Hyperlocal Delivery App                                   1
Mutual Fund Investment App                                                    1
IoT & SAAS Solutions for Transportation Industry                              1
ERP solutions provider                                                        1
B2B Finance & Fulfilment Network                                              1
Skill development and vocational training platform                            1
healthcare service aggregator                                                 1
Housing Finance For Low-Income Families                                       1
Real Estate content portal                                                    1
Online certification platform                                                 1
instant messaging platform                                                    1
Salon & Spa Aggregation & Discovery platform                                  1
Name: SubVertical, Length: 1942, dtype: int64

In [98]:
sfin.isna().sum()

Sr No                0
Date dd/mm/yyyy      0
Startup Name         0
Industry Vertical    171
SubVertical          936
City  Location       180
Investors Name       24
InvestmentnType      4
Amount in USD        960
Remarks              2625
dtype: int64

In [99]:
#irrelevant colums dropped
sfin.drop(['Sr No'],1,inplace=True)
sfin.drop(['Remarks'],1,inplace=True)

In [100]:
sfin.isna().sum()

Date dd/mm/yyyy      0
Startup Name         0
Industry Vertical    171
SubVertical          936
City  Location       180
Investors Name       24
InvestmentnType      4
Amount in USD        960
dtype: int64

In [101]:
#Date formating done and erroneous dates replace w/ NaT
sfin['date']=pd.to_datetime(sfin['Date dd/mm/yyyy'],errors='coerce')

In [102]:
sfin.head(10)

,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,date
0,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",2020-09-01
1,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",2020-01-13
2,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",2020-09-01
3,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",2020-02-01
4,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",2020-02-01
5,13/01/2020,Pando,Logistics,"Open-market, freight management platform",Chennai,Chiratae Ventures,Series A,"90,00,000",2020-01-13
6,10/01/2020,Zomato,Hospitality,Online Food Delivery Platform,Gurgaon,Ant Financial,Private Equity Round,"15,00,00,000",2020-10-01
7,12/12/2019,Ecozen,Technology,Agritech,Pune,Sathguru Catalyzer Advisors,Series A,"60,00,000",2019-12-12
8,06/12/2019,CarDekho,E-Commerce,Automobile,Gurgaon,Ping An Global Voyager Fund,Series D,"7,00,00,000",2019-06-12
9,03/12/2019,Dhruva Space,Aerospace,Satellite Communication,Bengaluru,"Mumbai Angels, Ravikanth Reddy",Seed,"5,00,00,000",2019-03-12

In [103]:
sfin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 9 columns):
Date dd/mm/yyyy      3044 non-null object
Startup Name         3044 non-null object
Industry Vertical    2873 non-null object
SubVertical          2108 non-null object
City  Location       2864 non-null object
Investors Name       3020 non-null object
InvestmentnType      3040 non-null object
Amount in USD        2084 non-null object
date                 3036 non-null datetime64[ns]
dtypes: datetime64[ns](1), object(8)
memory usage: 214.1+ KB

In [104]:
sfin.isna().sum()

Date dd/mm/yyyy      0
Startup Name         0
Industry Vertical    171
SubVertical          936
City  Location       180
Investors Name       24
InvestmentnType      4
Amount in USD        960
date                 8
dtype: int64

In [105]:
sfin['City  Location'].value_counts()

Bangalore                 700
Mumbai                    567
New Delhi                 421
Gurgaon                   287
Bengaluru                 141
Pune                      105
Hyderabad                 99
Chennai                   97
Noida                     92
Gurugram                  50
Ahmedabad                 38
Delhi                     34
Jaipur                    30
Kolkata                   21
Indore                    13
Chandigarh                11
Vadodara                  10
Goa                       10
Singapore                 8
Coimbatore                5
Pune / US                 4
\\xc2\\xa0Gurgaon         4
Kanpur                    4
Nagpur                    3
Faridabad                 3
\\xc2\\xa0New Delhi       3
Bhopal                    3
Kochi                     2
Siliguri                  2
Bangalore / SFO           2
                         ..
Menlo Park                1
USA/India                 1
Karur                     1
Delhi & Cambridge         1
California                1
Rourkela                  1
Hyderabad/USA             1
Bangalore / USA           1
Bhubaneswar               1
Mumbai / Global           1
Srinagar                  1
Pune / Dubai              1
Ahemdabad                 1
Belgaum                   1
Seattle / Bangalore       1
Taramani                  1
Haryana                   1
Missourie                 1
Noida / Singapore         1
SFO / Bangalore           1
New York                  1
Mumbai / UK               1
New Delhi / California    1
Burnsville                1
New York/ India           1
Bangalore / San Mateo     1
India                     1
Kolkatta                  1
Bangalore / Palo Alto     1
Palo Alto                 1
Name: City  Location, Length: 112, dtype: int64

In [106]:
#filling missing city locations w/ India_Other
sfin['City  Location']=sfin['City  Location'].fillna('India_Other')

In [107]:
sfin.isna().sum()

Date dd/mm/yyyy      0
Startup Name         0
Industry Vertical    171
SubVertical          936
City  Location       0
Investors Name       24
InvestmentnType      4
Amount in USD        960
date                 8
dtype: int64

In [108]:
sfin.tail()

,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,date
3039,29/01/2015,Printvenue,NaN,NaN,India_Other,Asia Pacific Internet Group,Private Equity,"45,00,000",2015-01-29
3040,29/01/2015,Graphene,NaN,NaN,India_Other,KARSEMVEN Fund,Private Equity,"8,25,000",2015-01-29
3041,30/01/2015,Mad Street Den,NaN,NaN,India_Other,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",2015-01-30
3042,30/01/2015,Simplotel,NaN,NaN,India_Other,MakeMyTrip,Private Equity,NaN,2015-01-30
3043,31/01/2015,couponmachine.in,NaN,NaN,India_Other,UK based Group of Angel Investors,Seed Funding,"1,40,000",2015-01-31

In [109]:
#replacing missing Industrial vertical data with 'unclassified'
sfin['Industry Vertical']=sfin['Industry Vertical'].fillna('Unclassified')

In [110]:
sfin.tail()

,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,date
3039,29/01/2015,Printvenue,Unclassified,NaN,India_Other,Asia Pacific Internet Group,Private Equity,"45,00,000",2015-01-29
3040,29/01/2015,Graphene,Unclassified,NaN,India_Other,KARSEMVEN Fund,Private Equity,"8,25,000",2015-01-29
3041,30/01/2015,Mad Street Den,Unclassified,NaN,India_Other,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",2015-01-30
3042,30/01/2015,Simplotel,Unclassified,NaN,India_Other,MakeMyTrip,Private Equity,NaN,2015-01-30
3043,31/01/2015,couponmachine.in,Unclassified,NaN,India_Other,UK based Group of Angel Investors,Seed Funding,"1,40,000",2015-01-31

In [111]:
#getting rid of ',' in amount and converting object to str to float
sfin['amount'] = sfin['Amount in USD'].str.replace(',','')
sfin['amount'] = pd.to_numeric(sfin['amount'], errors='coerce')

In [112]:
sfin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
Date dd/mm/yyyy      3044 non-null object
Startup Name         3044 non-null object
Industry Vertical    3044 non-null object
SubVertical          2108 non-null object
City  Location       3044 non-null object
Investors Name       3020 non-null object
InvestmentnType      3040 non-null object
Amount in USD        2084 non-null object
date                 3036 non-null datetime64[ns]
amount               2065 non-null float64
dtypes: datetime64[ns](1), float64(1), object(8)
memory usage: 237.9+ KB

In [113]:
sfin.tail()

,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,date,amount
3039,29/01/2015,Printvenue,Unclassified,NaN,India_Other,Asia Pacific Internet Group,Private Equity,"45,00,000",2015-01-29,4500000.0
3040,29/01/2015,Graphene,Unclassified,NaN,India_Other,KARSEMVEN Fund,Private Equity,"8,25,000",2015-01-29,825000.0
3041,30/01/2015,Mad Street Den,Unclassified,NaN,India_Other,"Exfinity Fund, GrowX Ventures.",Private Equity,"15,00,000",2015-01-30,1500000.0
3042,30/01/2015,Simplotel,Unclassified,NaN,India_Other,MakeMyTrip,Private Equity,NaN,2015-01-30,NaN
3043,31/01/2015,couponmachine.in,Unclassified,NaN,India_Other,UK based Group of Angel Investors,Seed Funding,"1,40,000",2015-01-31,140000.0

In [114]:
#dropping orginal amount column as no more relavent
sfin.drop(['Amount in USD'],1,inplace=True)

In [115]:
sfin.tail()

,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,date,amount
3039,29/01/2015,Printvenue,Unclassified,NaN,India_Other,Asia Pacific Internet Group,Private Equity,2015-01-29,4500000.0
3040,29/01/2015,Graphene,Unclassified,NaN,India_Other,KARSEMVEN Fund,Private Equity,2015-01-29,825000.0
3041,30/01/2015,Mad Street Den,Unclassified,NaN,India_Other,"Exfinity Fund, GrowX Ventures.",Private Equity,2015-01-30,1500000.0
3042,30/01/2015,Simplotel,Unclassified,NaN,India_Other,MakeMyTrip,Private Equity,2015-01-30,NaN
3043,31/01/2015,couponmachine.in,Unclassified,NaN,India_Other,UK based Group of Angel Investors,Seed Funding,2015-01-31,140000.0

In [116]:
#filling missing subvertical information w/ Industry vertical data
sfin['SubVertical']=sfin['SubVertical'].fillna(sfin['Industry Vertical'])

In [117]:
sfin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 9 columns):
Date dd/mm/yyyy      3044 non-null object
Startup Name         3044 non-null object
Industry Vertical    3044 non-null object
SubVertical          3044 non-null object
City  Location       3044 non-null object
Investors Name       3020 non-null object
InvestmentnType      3040 non-null object
date                 3036 non-null datetime64[ns]
amount               2065 non-null float64
dtypes: datetime64[ns](1), float64(1), object(7)
memory usage: 214.1+ KB

In [118]:
sfin['Investors Name'].mode()

0    Undisclosed Investors
dtype: object

In [119]:
#Original Date column dropped
sfin.drop(['Date dd/mm/yyyy'],1,inplace=True)

In [120]:
sfin.tail()

,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,date,amount
3039,Printvenue,Unclassified,Unclassified,India_Other,Asia Pacific Internet Group,Private Equity,2015-01-29,4500000.0
3040,Graphene,Unclassified,Unclassified,India_Other,KARSEMVEN Fund,Private Equity,2015-01-29,825000.0
3041,Mad Street Den,Unclassified,Unclassified,India_Other,"Exfinity Fund, GrowX Ventures.",Private Equity,2015-01-30,1500000.0
3042,Simplotel,Unclassified,Unclassified,India_Other,MakeMyTrip,Private Equity,2015-01-30,NaN
3043,couponmachine.in,Unclassified,Unclassified,India_Other,UK based Group of Angel Investors,Seed Funding,2015-01-31,140000.0

In [121]:
#replacing 8 missing date info with highest mode data 
sfin['date']=sfin['date'].fillna(sfin['date'].mode()[0])
# replace in missing 24 investor name with highest mode data - i.e., undisclosed investor
sfin['Investors Name']=sfin['Investors Name'].fillna(sfin['Investors Name'].mode()[0])

In [122]:
sfin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 8 columns):
Startup Name         3044 non-null object
Industry Vertical    3044 non-null object
SubVertical          3044 non-null object
City  Location       3044 non-null object
Investors Name       3044 non-null object
InvestmentnType      3040 non-null object
date                 3044 non-null datetime64[ns]
amount               2065 non-null float64
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 190.3+ KB

In [123]:
#Clean-up investment type - sorting into investment categories
sfin['InvestmentnType']=sfin['InvestmentnType'].str.lower()

In [124]:
sfin['InvestmentnType'].value_counts()

seed funding                   1356
private equity                 1356
seed/ angel funding            60
seed / angel funding           47
seed\\nfunding                 30
debt funding                   25
series a                       24
seed/angel funding             23
series b                       20
series c                       14
series d                       12
pre-series a                   8
angel / seed funding           8
seed round                     7
seed                           4
private equity round           4
seed / angle funding           3
series f                       2
crowd funding                  2
corporate round                2
venture round                  2
equity                         2
series e                       2
debt                           1
term loan                      1
series b (extension)           1
private                        1
debt-funding                   1
angel                          1
series h                       1
debt and preference capital    1
privateequity                  1
equity based funding           1
mezzanine                      1
seed funding round             1
private\\nequity               1
bridge round                   1
angel funding                  1
inhouse funding                1
maiden round                   1
angel round                    1
series g                       1
venture                        1
funding round                  1
pre series a                   1
venture - series unknown       1
single venture                 1
private funding                1
structured debt                1
series j                       1
Name: InvestmentnType, dtype: int64

In [125]:
private_angel=['seed funding','seed/ angel funding','seed / angel funding','seed\\nfunding','seed/angel funding','angel / seed funding','seed round','private equity round','seed,seed / angle funding','seed funding round','private','single venture','angel funding','angel round','private\\nequity','seed / angle funding', 'seed\\\\nfunding', 'private\\\\nequity','privateequity','private funding','angel','seed','private equity']

In [126]:
venture_capital=['venture round','venture - series unknown','venture','single venture','corporate round']

In [127]:
pre_series_A_B=['pre-series a','series a','series b','pre series a','series b (extension)']

In [128]:
series_C_H=['series c','series d','series f','series e','series j','series g','series h']

In [129]:
debt_fund=['debt funding','term loan','structured debt','debt-funding','debt and preference capital','debt']

In [130]:
other_funding=['crowd funding','mezzanine','maiden round','funding round','bridge round','inhouse funding','equity based funding','equity']

In [131]:
sfin['invst_type_sorted']=sfin['InvestmentnType']

In [132]:
for x in sfin['invst_type_sorted']:
    if x in private_angel:
        sfin['invst_type_sorted'] = sfin['invst_type_sorted'].replace(to_replace=x, value='private_angel')
    elif x in venture_capital:
        sfin['invst_type_sorted'] = sfin['invst_type_sorted'].replace(to_replace=x, value='venture_capital')
    elif x in pre_series_A_B:
        sfin['invst_type_sorted'] = sfin['invst_type_sorted'].replace(to_replace=x, value='pre_series_A_B')
    elif x in series_C_H:
        sfin['invst_type_sorted'] = sfin['invst_type_sorted'].replace(to_replace=x, value='series_C_H')
    elif x in debt_fund:
        sfin['invst_type_sorted'] = sfin['invst_type_sorted'].replace(to_replace=x, value='debt_fund')
    elif x in other_funding:
        sfin['invst_type_sorted'] = sfin['invst_type_sorted'].replace(to_replace=x, value='other_funding')

In [133]:
sfin['invst_type_sorted'].unique()

array(['private_angel', 'series_C_H', 'pre_series_A_B', 'debt_fund',
       'venture_capital', nan, 'other_funding'], dtype=object)

In [134]:
#fill missing investment type with other funding
sfin['invst_type_sorted']=sfin['invst_type_sorted'].fillna('other_funding')

In [135]:
sfin['invst_type_sorted'].value_counts()

private_angel      2907
pre_series_A_B     54
series_C_H         33
debt_fund          30
other_funding      14
venture_capital    6
Name: invst_type_sorted, dtype: int64

In [136]:
sfin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 9 columns):
Startup Name         3044 non-null object
Industry Vertical    3044 non-null object
SubVertical          3044 non-null object
City  Location       3044 non-null object
Investors Name       3044 non-null object
InvestmentnType      3040 non-null object
date                 3044 non-null datetime64[ns]
amount               2065 non-null float64
invst_type_sorted    3044 non-null object
dtypes: datetime64[ns](1), float64(1), object(7)
memory usage: 214.1+ KB

In [137]:
#Clean-up city data
sfin['City  Location'].unique()

array(['Bengaluru', 'Gurgaon', 'New Delhi', 'Mumbai', 'Chennai', 'Pune',
       'Noida', 'Faridabad', 'San Francisco', 'San Jose,', 'Amritsar',
       'Delhi', 'Kormangala', 'Tulangan', 'Hyderabad', 'Burnsville',
       'Menlo Park', 'Gurugram', 'Palo Alto', 'Santa Monica', 'Singapore',
       'Taramani', 'Andheri', 'Chembur', 'Nairobi', 'Haryana', 'New York',
       'Karnataka', 'Mumbai/Bengaluru', 'Bhopal',
       'Bengaluru and Gurugram', 'India/Singapore', 'Jaipur', 'India/US',
       'Nagpur', 'Indore', 'New York, Bengaluru', 'California', 'India',
       'Ahemadabad', 'Rourkela', 'Srinagar', 'Bhubneswar', 'Chandigarh',
       'Delhi & Cambridge', 'Kolkatta', 'Kolkata', 'Coimbatore',
       'Bangalore', 'Udaipur', 'India_Other', 'Ahemdabad', 'Bhubaneswar',
       'Ahmedabad', 'Surat', 'Goa', 'Uttar Pradesh', 'Nw Delhi', 'Gaya',
       'Vadodara', 'Trivandrum', 'Missourie', 'Panaji', 'Gwalior',
       'Karur', 'Udupi', 'Kochi', 'Agra', 'Bangalore/ Bangkok', 'Hubli',
       'Kerala', 'Kozhikode', 'US', 'Siliguri', 'USA', 'Lucknow',
       'Kanpur', 'SFO / Bangalore', 'London', 'Seattle / Bangalore',
       'Pune/Seattle', 'Pune / Dubai', 'Bangalore / SFO', 'Varanasi',
       'New Delhi / US', 'Mumbai / UK', 'Jodhpur', 'Hyderabad/USA',
       'Boston', 'Bangalore / Palo Alto', 'Mumbai / NY', 'USA/India',
       'Goa/Hyderabad', 'Noida / Singapore', 'Belgaum', 'Pune / US',
       'Chennai/ Singapore', 'Pune / Singapore', 'Bangalore / San Mateo',
       'New York/ India', 'US/India', 'Gurgaon / SFO', 'Bangalore / USA',
       'New Delhi/ Houston', 'Mumbai / Global', 'India / US',
       '\\\\xc2\\\\xa0Noida', '\\\\xc2\\\\xa0Bangalore',
       '\\\\xc2\\\\xa0Gurgaon', '\\\\xc2\\\\xa0New Delhi',
       '\\\\xc2\\\\xa0Mumbai', 'New Delhi / California',
       'Dallas / Hyderabad'], dtype=object)

In [138]:
sfin['City  Location'].value_counts()

Bangalore                 700
Mumbai                    567
New Delhi                 421
Gurgaon                   287
India_Other               180
Bengaluru                 141
Pune                      105
Hyderabad                 99
Chennai                   97
Noida                     92
Gurugram                  50
Ahmedabad                 38
Delhi                     34
Jaipur                    30
Kolkata                   21
Indore                    13
Chandigarh                11
Vadodara                  10
Goa                       10
Singapore                 8
Coimbatore                5
Pune / US                 4
Kanpur                    4
\\xc2\\xa0Gurgaon         4
Nagpur                    3
Faridabad                 3
\\xc2\\xa0New Delhi       3
Bhopal                    3
Kochi                     2
Siliguri                  2
                         ..
Menlo Park                1
USA/India                 1
Karur                     1
Delhi & Cambridge         1
California                1
Rourkela                  1
Hyderabad/USA             1
Bangalore / USA           1
Bhubaneswar               1
Mumbai / Global           1
Srinagar                  1
Pune / Dubai              1
Ahemdabad                 1
Belgaum                   1
Seattle / Bangalore       1
Taramani                  1
Haryana                   1
Missourie                 1
Noida / Singapore         1
SFO / Bangalore           1
New York                  1
Mumbai / UK               1
New Delhi / California    1
Burnsville                1
New York/ India           1
Bangalore / San Mateo     1
India                     1
Kolkatta                  1
Bangalore / Palo Alto     1
Palo Alto                 1
Name: City  Location, Length: 113, dtype: int64

In [139]:
#Create Top 6 city list
Delhi_NCR=['New Delhi','Gurgaon','Noida','Gurugram','Faridabad','Delhi','Delhi & Cambridge','New Delhi / US','Gurgaon / SFO','New Delhi / California','Noida / Singapore',
    'New Delhi/ Houston','\\\\xc2\\\\xa0Noida','\\\\xc2\\\\xa0Gurgaon', '\\\\xc2\\\\xa0New Delhi','New Delhi / California','Nw Delhi']
Bengaluru_area=['Bengaluru','Bangalore','Bangalore/ Bangkok','SFO / Bangalore','Seattle / Bangalore','Bangalore / SFO','Bangalore / Palo Alto','Bangalore / San Mateo','Bangalore / USA','\\\\xc2\\\\xa0Bangalore','Kormangala','New York, Bengaluru']
Mumbai_area = ['Mumbai','Andheri', 'Chembur','Mumbai / UK','Mumbai / NY','Mumbai / Global','\\\\xc2\\\\xa0Mumbai']
Pune_area=['Pune','Pune/Seattle', 'Pune / Dubai','Pune / US','Pune / Singapore']
Hyderabad_area=['Hyderabad','Hyderabad/USA','Dallas / Hyderabad']
Chennai_area=['Chennai','Taramani','Chennai/ Singapore']

In [140]:
sfin['Sorted_Cities']=sfin['City  Location']
for x in sfin['Sorted_Cities']:
    if x in Delhi_NCR:
        sfin['Sorted_Cities'] = sfin['Sorted_Cities'].replace(to_replace=x, value='Delhi_NCR')
    elif x in Bengaluru_area:
        sfin['Sorted_Cities'] = sfin['Sorted_Cities'].replace(to_replace=x, value='Bengaluru_area')
    elif x in Mumbai_area:
        sfin['Sorted_Cities'] = sfin['Sorted_Cities'].replace(to_replace=x, value='Mumbai_area')
    elif x in Pune_area:
        sfin['Sorted_Cities'] = sfin['Sorted_Cities'].replace(to_replace=x, value='Pune_area')
    elif x in Hyderabad_area:
        sfin['Sorted_Cities'] = sfin['Sorted_Cities'].replace(to_replace=x, value='Hyderabad_area')
    elif x in Chennai_area:
        sfin['Sorted_Cities'] = sfin['Sorted_Cities'].replace(to_replace=x, value='Chennai_area')

In [141]:
sfin['Sorted_Cities'].unique()

array(['Bengaluru_area', 'Delhi_NCR', 'Mumbai_area', 'Chennai_area',
       'Pune_area', 'San Francisco', 'San Jose,', 'Amritsar', 'Tulangan',
       'Hyderabad_area', 'Burnsville', 'Menlo Park', 'Palo Alto',
       'Santa Monica', 'Singapore', 'Nairobi', 'Haryana', 'New York',
       'Karnataka', 'Mumbai/Bengaluru', 'Bhopal',
       'Bengaluru and Gurugram', 'India/Singapore', 'Jaipur', 'India/US',
       'Nagpur', 'Indore', 'California', 'India', 'Ahemadabad',
       'Rourkela', 'Srinagar', 'Bhubneswar', 'Chandigarh', 'Kolkatta',
       'Kolkata', 'Coimbatore', 'Udaipur', 'India_Other', 'Ahemdabad',
       'Bhubaneswar', 'Ahmedabad', 'Surat', 'Goa', 'Uttar Pradesh',
       'Gaya', 'Vadodara', 'Trivandrum', 'Missourie', 'Panaji', 'Gwalior',
       'Karur', 'Udupi', 'Kochi', 'Agra', 'Hubli', 'Kerala', 'Kozhikode',
       'US', 'Siliguri', 'USA', 'Lucknow', 'Kanpur', 'London', 'Varanasi',
       'Jodhpur', 'Boston', 'USA/India', 'Goa/Hyderabad', 'Belgaum',
       'New York/ India', 'US/India', 'India / US'], dtype=object)

In [142]:
sfin['Sorted_Cities'].value_counts()

Delhi_NCR           903
Bengaluru_area      854
Mumbai_area         573
India_Other         180
Pune_area           112
Hyderabad_area      101
Chennai_area        99
Ahmedabad           38
Jaipur              30
Kolkata             21
Indore              13
Chandigarh          11
Goa                 10
Vadodara            10
Singapore           8
Coimbatore          5
Kanpur              4
Nagpur              3
Bhopal              3
San Francisco       2
Udaipur             2
Kochi               2
Siliguri            2
Udupi               2
India/US            2
Gwalior             2
Surat               2
Agra                2
Mumbai/Bengaluru    2
Ahemadabad          2
                   ..
Boston              1
Varanasi            1
US/India            1
Jodhpur             1
Uttar Pradesh       1
Tulangan            1
Santa Monica        1
India/Singapore     1
Rourkela            1
California          1
Karur               1
Menlo Park          1
Lucknow             1
India / US          1
Goa/Hyderabad       1
Nairobi             1
London              1
Kozhikode           1
Bhubaneswar         1
New York            1
Kolkatta            1
India               1
New York/ India     1
USA/India           1
Burnsville          1
Srinagar            1
Missourie           1
Belgaum             1
Ahemdabad           1
Palo Alto           1
Name: Sorted_Cities, Length: 73, dtype: int64

In [143]:
top_6_cities = ['Delhi_NCR','Bengaluru_area','Mumbai_area','Pune_area','Hyderabad_area','Chennai_area']

In [144]:
for x in sfin['Sorted_Cities']:
    if x in top_6_cities:
        sfin['Sorted_Cities'] = sfin['Sorted_Cities']
    else:
        sfin['Sorted_Cities'] = sfin['Sorted_Cities'].replace(to_replace=x, value='Others')

In [145]:
sfin['Sorted_Cities'].value_counts()

Delhi_NCR         903
Bengaluru_area    854
Mumbai_area       573
Others            402
Pune_area         112
Hyderabad_area    101
Chennai_area      99
Name: Sorted_Cities, dtype: int64

In [146]:
sfin.head()

,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,date,amount,invst_type_sorted,Sorted_Cities
0,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,private equity round,2020-09-01,200000000.0,private_angel,Bengaluru_area
1,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,series c,2020-01-13,8048394.0,series_C_H,Delhi_NCR
2,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,series b,2020-09-01,18358860.0,pre_series_A_B,Bengaluru_area
3,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,pre-series a,2020-02-01,3000000.0,pre_series_A_B,Delhi_NCR
4,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,seed round,2020-02-01,1800000.0,private_angel,Mumbai_area

In [147]:
sfin['industry_vertical']=sfin['Industry Vertical'].str.lower()
sfin['SubVertical']=sfin['SubVertical'].str.lower()
sfin['sort_ind_vert']=sfin['SubVertical']

In [148]:
sfin.head()

,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,date,amount,invst_type_sorted,Sorted_Cities,industry_vertical,sort_ind_vert
0,BYJU’S,E-Tech,e-learning,Bengaluru,Tiger Global Management,private equity round,2020-09-01,200000000.0,private_angel,Bengaluru_area,e-tech,e-learning
1,Shuttl,Transportation,app based shuttle service,Gurgaon,Susquehanna Growth Equity,series c,2020-01-13,8048394.0,series_C_H,Delhi_NCR,transportation,app based shuttle service
2,Mamaearth,E-commerce,retailer of baby and toddler products,Bengaluru,Sequoia Capital India,series b,2020-09-01,18358860.0,pre_series_A_B,Bengaluru_area,e-commerce,retailer of baby and toddler products
3,https://www.wealthbucket.in/,FinTech,online investment,New Delhi,Vinod Khatumal,pre-series a,2020-02-01,3000000.0,pre_series_A_B,Delhi_NCR,fintech,online investment
4,Fashor,Fashion and Apparel,embroiled clothes for women,Mumbai,Sprout Venture Partners,seed round,2020-02-01,1800000.0,private_angel,Mumbai_area,fashion and apparel,embroiled clothes for women

In [149]:
sfin.drop(['Industry Vertical'],1,inplace=True)
"""# replacing generic classifications like Consumer Internet, Technology with Sub-verticle data
sfin.sort_ind_vert.replace('consumer internet',sfin.SubVertical,inplace=True)
sfin.sort_ind_vert.replace('technology',sfin.SubVertical,inplace=True)"""

"# replacing generic classifications like Consumer Internet, Technology with Sub-verticle data\nsfin.sort_ind_vert.replace('consumer internet',sfin.SubVertical,inplace=True)\nsfin.sort_ind_vert.replace('technology',sfin.SubVertical,inplace=True)"

In [150]:
sfin['sort_ind_vert'].value_counts()

unclassified                                               171
online lending platform                                    21
food delivery platform                                     14
online pharmacy                                            11
online education platform                                  10
online learning platform                                   10
online food delivery                                       9
online payment gateway                                     6
online marketplace                                         6
data analytics platform                                    5
online consumer lending platform                           5
ecommerce marketplace                                      5
education                                                  5
health-tech platform                                       5
online food delivery platform                              5
online lending                                             5
non-banking financial company                              5
online insurance platform                                  4
online insurance aggregator                                4
micro lending platform                                     4
customer engagement platform                               4
co-working spaces                                          4
hyperlocal handyman services                               4
ecommerce                                                  4
online gifting platform                                    4
big data & analytics platform                              3
healthy food delivery platform                             3
online furniture store                                     3
fashion discovery platform                                 3
e-learning                                                 3
                                                          ..
ai based fashion search portal                             1
cancer radiology                                           1
auto spare parts etailer                                   1
womens fashion wear portal                                 1
startup focused online publisher                           1
marketing automation platform                              1
online legal services platform                             1
crowdsourced delivery platform                             1
enterprise work management software                        1
online jon portal                                          1
end-to-end logistics platform                              1
treatment development for antibiotic-resistant diseases    1
budget hotels brand & aggregator platform                  1
sales & productivity software                              1
online logistics marketplace                               1
stay & travel related services                             1
professional service appointment booking service           1
hyperlocal\\xc2\\xa0 grocery delivery service              1
ethnic beverages manufacturer                              1
personal device assistant app                              1
hygiene                                                    1
global healthcare products                                 1
sustainable agri-inputs firm                               1
tech accessories e-tailer                                  1
ad network                                                 1
workspace rentals                                          1
lifestyle ecommerce portal                                 1
fashion jewelry and accessories e-tailer                   1
price comparison                                           1
car maintenance & management mobile app                    1
Name: sort_ind_vert, Length: 2535, dtype: int64

In [151]:
#start of cleaning process
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace='-', value='', regex=True)
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=' & ', value='_', regex=True)
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace='app', value='', regex=True)
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=' and ', value='_', regex=True)

In [152]:
# Finding the keywords
srt=sfin['sort_ind_vert']
from collections import Counter
p = Counter(" ".join(srt).split()).most_common(60)
result = pd.DataFrame(p, columns=['Word', 'Frequency'])
print(result)

            Word  Frequency
0   platform      1020
1   online        607
2   mobile        254
3   marketplace   230
4   for           198
5   unclassified  171
6   services      152
7   solutions     138
8   based         126
9   service       98
10  food          94
11  portal        93
12  provider      91
13  lending       86
14  delivery      85
15  etailer       85
16  management    82
17  ecommerce     79
18  aggregator    73
19  fashion       69
20  rental        64
21  discovery     61
22  logistics     59
23  healthcare    58
24  hyperlocal    56
25  home          54
26  education     53
27  software      52
28  social        51
29  learning      51
30  products      49
31  digital       48
32  booking       45
33  analytics     44
34  data          43
35  ondemand      42
36  startup       41
37  health        38
38  b2b           36
39  solution      36
40  car           35
41  chain         34
42  product       34
43  tech          34
44  travel        33
45  cloud         33
46  grocery       32
47  saas          32
48  store         31
49  company       30
50  network       30
51  content       30
52  technology    29
53  manufacturer  29
54  hotel         28
55  financial     27
56  to            27
57  medical       25
58  fitness       25
59  real          23

In [153]:
#checking against top services, markets
sfin['sort_ind_vert'].value_counts()

unclassified                                   171
online lending platform                        21
food delivery platform                         14
online pharmacy                                11
online learning platform                       10
online education platform                      10
online food delivery                           9
online marketplace                             6
online payment gateway                         6
online food delivery platform                  5
data analytics platform                        5
ecommerce marketplace                          5
online consumer lending platform               5
nonbanking financial company                   5
education                                      5
agritech                                       5
online lending                                 5
healthtech platform                            5
online insurance platform                      4
elearning                                      4
ecommerce                                      4
customer engagement platform                   4
online gifting platform                        4
fashion etailer                                4
hyperlocal handyman services                   4
micro lending platform                         4
coworking spaces                               4
online insurance aggregator                    4
online test preparation platform               3
artificial intelligence platform               3
                                              ..
healthcare training programs                   1
mobile payment software platform               1
personalized fashion                           1
online hotel reservation platform              1
online credit management tools                 1
bicycle sharing platform                       1
mutual fund investing platform                 1
home improvement marketplace                   1
specialty tea etailer                          1
private fashion brand etailer                  1
online car servicing booking platform          1
fintech platform                               1
social network for healthcare professionals    1
 based fitness coaching                        1
womens fashion wear portal                     1
credit + payment mobile                        1
mobile  based job search                       1
ai based fashion search portal                 1
microdelivery grocery startup                  1
cancer radiology                               1
auto spare parts etailer                       1
startup focused online publisher               1
online mf investment platform                  1
marketing automation platform                  1
online legal services platform                 1
it / customer engagement consulting            1
enterprise work management software            1
crossdevice retargeting platform               1
online jon portal                              1
cloud data integration platform                1
Name: sort_ind_vert, Length: 2526, dtype: int64

In [154]:
#long and painful process of sorting and cleaning data based on key words, target >80% w/o unclassified data accounted for
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('food')], value='food_beverages_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('health')], value='meditech_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('transport')], value='transport_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('logistics')], value='logistics_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('education')], value='edtech_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('edtech')], value='edtech_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('learning')], value='edtech_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('hyperlocal')], value='hyperlocal_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('fin')], value='fintech_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('marketplace')], value='marketplace_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('software')], value='software_cloud_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('cloud')], value='software_cloud_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('restaurant')], value='food_beverages_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('ecommerce')], value='ecommerce_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('data')], value='AI_Data_analytics_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('intelligence')], value='AI_Data_analytics_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('analytics')], value='AI_Data_analytics_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('estate')], value='real_estate_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('real estate')], value='real_estate_services')

In [155]:
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('lending')], value='fintech_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('etailer')], value='lifestyle_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('fashion')], value='lifestyle_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('agri')], value='agritech_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('medic')], value='meditech_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('grocery')], value='ecommerce_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('payment')], value='fintech_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('pharmacy')], value='meditech_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('hotel')], value='travel_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('travel')], value='travel_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('insurance')], value='fintech_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('doctor')], value='meditech_industry')

In [156]:
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('assistant')], value='AI_Data_analytics_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('investment')], value='fintech_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('bike')], value='transport_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('taxi')], value='transport_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('electric')], value='transport_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('pooling')], value='transport_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('care')], value='lifestyle_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('card')], value='fintech_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('car')], value='transport_industry')

In [157]:
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('beauty')], value='lifestyle_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('loan')], value='fintech_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('wallet')], value='fintech_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('funding')], value='fintech_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('commerce')], value='ecommerce_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('truck')], value='logistics_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('vehicle')], value='transport_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('cab')], value='transport_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('automo')], value='transport_industry')#automotive, automobile
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('freight')], value='logistics_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('online')], value='online_and_booking_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('booking')], value='online_and_booking_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('entertainment')], value='media_entertainment_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('social')], value='media_entertainment_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('ondemand')], value='online_and_booking_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('mile')], value='logistics_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('marketing')], value='media_entertainment_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('news')], value='media_entertainment_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('media')], value='media_entertainment_services')

In [158]:
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('fitness')], value='lifestyle_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('saas')], value='software_cloud_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('video')], value='media_entertainment_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('securinformation')], value='software_cloud_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('scooter')], value='transport_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('gam')], value='media_entertainment_services')#gaming
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('employee')], value='b2b_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('b2b')], value='b2b_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('enterprise')], value='b2b_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('mobile')], value='online_and_booking_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('property')], value='real_estate_services')

In [159]:
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('wealth')], value='fintech_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('home')], value='lifestyle_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('interior')], value='lifestyle_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('parking')], value='transport_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('ticket')], value='ecommerce_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('delivery')], value='hyperlocal_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('discovery')], value='lifestyle_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('cancer')], value='meditech_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('energy')], value='energy_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('solar')], value='energy_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('cyber')], value='software_cloud_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('diag')], value='meditech_industry')

In [160]:
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('shuttle')], value='transport_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('money')], value='fintech_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('clinic')], value='meditech_industry')

In [161]:
#testing 'key word' for sorting data
i = ['data','analytics']
sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('clinic',regex=True)]

Series([], Name: sort_ind_vert, dtype: object)

In [162]:
#Indentifying the top key words for sorting
srt=sfin['sort_ind_vert']
from collections import Counter
p = Counter(" ".join(srt).split()).most_common(60)
result = pd.DataFrame(p, columns=['Word', 'Frequency'])
print(result)

                            Word  Frequency
0   online_and_booking_services   346
1   fintech_services              267
2   lifestyle_services            229
3   meditech_industry             206
4   marketplace_services          205
5   unclassified                  171
6   platform                      163
7   edtech_industry               135
8   food_beverages_industry       131
9   media_entertainment_services  121
10  transport_industry            119
11  AI_Data_analytics_services    108
12  software_cloud_services       106
13  ecommerce_industry            105
14  logistics_industry            86
15  hyperlocal_services           62
16  travel_industry               58
17  for                           35
18  solutions                     30
19  real_estate_services          25
20  management                    24
21  services                      24
22  provider                      22
23  b2b_services                  21
24  chain                         19
25  based                         19
26  aggregator                    19
27  agritech_industry             17
28  service                       17
29  energy_industry               16
30  manufacturer                  15
31  portal                        13
32  solution                      11
33  tech                          11
34  startup                       11
35  engagement                    10
36  coworking                     10
37  ai                            9
38  digital                       9
39  technology                    9
40  reality                       9
41  spaces                        9
42  product                       8
43  virtual                       8
44  rental                        8
45  on                            8
46  automation                    7
47  of                            7
48  job                           7
49  content                       7
50  supply                        6
51  customer                      6
52  company                       6
53  products                      6
54  iot                           6
55  demand                        6
56  internet                      6
57  women                         5
58  development                   5
59  recognition                   5

In [163]:
top_services = ['online_and_booking_services','fintech_services','lifestyle_services','marketplace_services','meditech_industry','unclassified','edtech_industry','online_services','edtech_industry','food_beverages_industry','media_entertainment_services','transport_industry','AI_Data_analytics_services','software_cloud_services',
                'ecommerce_industry','logistics_industry','hyperlocal_services','travel_industry','real_estate_services','b2b_services','agritech_industry','energy_industry']

In [164]:
print(top_services)

['online_and_booking_services', 'fintech_services', 'lifestyle_services', 'marketplace_services', 'meditech_industry', 'unclassified', 'edtech_industry', 'online_services', 'edtech_industry', 'food_beverages_industry', 'media_entertainment_services', 'transport_industry', 'AI_Data_analytics_services', 'software_cloud_services', 'ecommerce_industry', 'logistics_industry', 'hyperlocal_services', 'travel_industry', 'real_estate_services', 'b2b_services', 'agritech_industry', 'energy_industry']

In [165]:
sfin.head(10)

,Startup Name,SubVertical,City Location,Investors Name,InvestmentnType,date,amount,invst_type_sorted,Sorted_Cities,industry_vertical,sort_ind_vert
0,BYJU’S,e-learning,Bengaluru,Tiger Global Management,private equity round,2020-09-01,200000000.0,private_angel,Bengaluru_area,e-tech,edtech_industry
1,Shuttl,app based shuttle service,Gurgaon,Susquehanna Growth Equity,series c,2020-01-13,8048394.0,series_C_H,Delhi_NCR,transportation,transport_industry
2,Mamaearth,retailer of baby and toddler products,Bengaluru,Sequoia Capital India,series b,2020-09-01,18358860.0,pre_series_A_B,Bengaluru_area,e-commerce,lifestyle_services
3,https://www.wealthbucket.in/,online investment,New Delhi,Vinod Khatumal,pre-series a,2020-02-01,3000000.0,pre_series_A_B,Delhi_NCR,fintech,fintech_services
4,Fashor,embroiled clothes for women,Mumbai,Sprout Venture Partners,seed round,2020-02-01,1800000.0,private_angel,Mumbai_area,fashion and apparel,embroiled clothes for women
5,Pando,"open-market, freight management platform",Chennai,Chiratae Ventures,series a,2020-01-13,9000000.0,pre_series_A_B,Chennai_area,logistics,logistics_industry
6,Zomato,online food delivery platform,Gurgaon,Ant Financial,private equity round,2020-10-01,150000000.0,private_angel,Delhi_NCR,hospitality,food_beverages_industry
7,Ecozen,agritech,Pune,Sathguru Catalyzer Advisors,series a,2019-12-12,6000000.0,pre_series_A_B,Pune_area,technology,agritech_industry
8,CarDekho,automobile,Gurgaon,Ping An Global Voyager Fund,series d,2019-06-12,70000000.0,series_C_H,Delhi_NCR,e-commerce,transport_industry
9,Dhruva Space,satellite communication,Bengaluru,"Mumbai Angels, Ravikanth Reddy",seed,2019-03-12,50000000.0,private_angel,Bengaluru_area,aerospace,satellite communication

In [166]:
# Convert unstorable data to 'Unsorted services'
for x in sfin['sort_ind_vert']:
    if x in top_services:
        sfin['sort_ind_vert'] = sfin['sort_ind_vert']
    else:
        sfin['sort_ind_vert'] = sfin['sort_ind_vert'].replace(to_replace=x, value='unsorted_services')

In [168]:
sfin.head()

,Startup Name,SubVertical,City Location,Investors Name,InvestmentnType,date,amount,invst_type_sorted,Sorted_Cities,industry_vertical,sort_ind_vert
0,BYJU’S,e-learning,Bengaluru,Tiger Global Management,private equity round,2020-09-01,200000000.0,private_angel,Bengaluru_area,e-tech,edtech_industry
1,Shuttl,app based shuttle service,Gurgaon,Susquehanna Growth Equity,series c,2020-01-13,8048394.0,series_C_H,Delhi_NCR,transportation,transport_industry
2,Mamaearth,retailer of baby and toddler products,Bengaluru,Sequoia Capital India,series b,2020-09-01,18358860.0,pre_series_A_B,Bengaluru_area,e-commerce,lifestyle_services
3,https://www.wealthbucket.in/,online investment,New Delhi,Vinod Khatumal,pre-series a,2020-02-01,3000000.0,pre_series_A_B,Delhi_NCR,fintech,fintech_services
4,Fashor,embroiled clothes for women,Mumbai,Sprout Venture Partners,seed round,2020-02-01,1800000.0,private_angel,Mumbai_area,fashion and apparel,unsorted_services

In [169]:
#still not meeting >80% target, to further improve unsorted use data from industry vertical instead of sub-vertical only for unsorted data
sfin.sort_ind_vert.replace('unsorted_services',sfin.industry_vertical,inplace=True)

In [171]:
sfin.head()

,Startup Name,SubVertical,City Location,Investors Name,InvestmentnType,date,amount,invst_type_sorted,Sorted_Cities,industry_vertical,sort_ind_vert
0,BYJU’S,e-learning,Bengaluru,Tiger Global Management,private equity round,2020-09-01,200000000.0,private_angel,Bengaluru_area,e-tech,edtech_industry
1,Shuttl,app based shuttle service,Gurgaon,Susquehanna Growth Equity,series c,2020-01-13,8048394.0,series_C_H,Delhi_NCR,transportation,transport_industry
2,Mamaearth,retailer of baby and toddler products,Bengaluru,Sequoia Capital India,series b,2020-09-01,18358860.0,pre_series_A_B,Bengaluru_area,e-commerce,lifestyle_services
3,https://www.wealthbucket.in/,online investment,New Delhi,Vinod Khatumal,pre-series a,2020-02-01,3000000.0,pre_series_A_B,Delhi_NCR,fintech,fintech_services
4,Fashor,embroiled clothes for women,Mumbai,Sprout Venture Partners,seed round,2020-02-01,1800000.0,private_angel,Mumbai_area,fashion and apparel,fashion and apparel

In [172]:
sfin['sort_ind_vert'].value_counts()

online_and_booking_services                     346
fintech_services                                267
lifestyle_services                              229
meditech_industry                               206
marketplace_services                            205
unclassified                                    171
edtech_industry                                 135
consumer internet                               132
food_beverages_industry                         131
technology                                      129
media_entertainment_services                    121
transport_industry                              119
AI_Data_analytics_services                      108
software_cloud_services                         106
ecommerce_industry                              105
logistics_industry                              86
hyperlocal_services                             62
travel_industry                                 58
real_estate_services                            25
b2b_services                                    21
agritech_industry                               17
energy_industry                                 16
healthcare                                      15
food & beverage                                 14
ecommerce                                       11
finance                                         8
e-commerce                                      7
logistics                                       6
food and beverage                               5
real estate                                     5
                                               ..
fashion and apparel                             1
nanotechnology                                  1
job board                                       1
probiotic technology products manufacturer      1
architectural design & consulting               1
self-storage spaces                             1
public commute helper app                       1
luxury label                                    1
physical storage warehouses                     1
used gadgets buy / refurbishing                 1
digital & physical publishing platform          1
kids tool kit for innovation platform           1
location based app                              1
transportation                                  1
spam call block app                             1
tech enabled ac bus service                     1
cross-channel crm platform                      1
document digitization platform                  1
coupon aggregator platform                      1
non profit organization to alleviate poverty    1
budget accommodation aggregator                 1
music streaming app                             1
holiday resort chain                            1
location based engagement & rewards platform    1
fund raising platform for startups              1
prepaid bill manager app                        1
automated storage & warehousing solution        1
it                                              1
mutual fund investing platform                  1
product customization platform                  1
Name: sort_ind_vert, Length: 187, dtype: int64

In [201]:
# final sorting checked and stopped at ~81% of data without 'unclassified' and 'unsorted'
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('commerce')], value='ecommerce_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('health')], value='meditech_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('food')], value='food_beverages_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('fin')], value='fintech_services')#financial, finance, fin-tech..
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('logistics')], value='logistics_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('education')], value='edtech_industry')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('real estate')], value='real_estate_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('fashion')], value='lifestyle_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('software')], value='software_cloud_services')
sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('apparel')], value='lifestyle_services')

#sfin['sort_ind_vert']=sfin['sort_ind_vert'].replace(to_replace=sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('education')], value='edtech_industry')

In [202]:
# Finding the keywords
srt=sfin['sort_ind_vert']
from collections import Counter
p = Counter(" ".join(srt).split()).most_common(60)
result = pd.DataFrame(p, columns=['Word', 'Frequency'])
print(result)

                            Word  Frequency
0   online_and_booking_services   346
1   fintech_services              278
2   lifestyle_services            234
3   meditech_industry             224
4   marketplace_services          205
5   unclassified                  171
6   food_beverages_industry       153
7   edtech_industry               140
8   internet                      135
9   consumer                      132
10  technology                    131
11  ecommerce_industry            123
12  media_entertainment_services  121
13  transport_industry            119
14  software_cloud_services       108
15  AI_Data_analytics_services    108
16  logistics_industry            92
17  hyperlocal_services           62
18  travel_industry               58
19  platform                      51
20  real_estate_services          30
21  b2b_services                  21
22  agritech_industry             17
23  energy_industry               16
24  app                           15
25  &                             10
26  service                       9
27  management                    9
28  services                      8
29  for                           6
30  others                        5
31  chain                         5
32  engagement                    5
33  based                         5
34  manufacturer                  5
35  customer                      4
36  tech                          4
37  digital                       4
38  aggregator                    4
39  and                           4
40  rental                        4
41  job                           4
42  waste                         3
43  it                            3
44  publishing                    3
45  government                    3
46  on                            3
47  demand                        3
48  content                       3
49  web                           3
50  board                         3
51  accommodation                 3
52  search                        3
53  location                      3
54  preparation                   3
55  of                            3
56  fund                          3
57  consulting                    3
58  solutions                     3
59  luxury                        2

In [203]:
sfin['sort_ind_vert'].value_counts()

online_and_booking_services                                 346
fintech_services                                            278
lifestyle_services                                          234
meditech_industry                                           224
marketplace_services                                        205
unclassified                                                171
food_beverages_industry                                     153
edtech_industry                                             140
consumer internet                                           132
technology                                                  129
ecommerce_industry                                          123
media_entertainment_services                                121
transport_industry                                          119
software_cloud_services                                     108
AI_Data_analytics_services                                  108
logistics_industry                                          92
hyperlocal_services                                         62
travel_industry                                             58
real_estate_services                                        30
b2b_services                                                21
agritech_industry                                           17
energy_industry                                             16
others                                                      5
inspiration                                                 2
residential rental management platform                      2
services                                                    2
waste management service                                    2
interface development platform for government officials     2
customer engagement platform                                2
internet of things platform                                 2
                                                           ..
clean tech                                                  1
dairy based product manufacturer                            1
probiotic technology products manufacturer                  1
360-degree view creating platform                           1
wedding planning platform                                   1
agriculture                                                 1
speech recognition solutions                                1
waste management solutions                                  1
job board                                                   1
self-storage spaces                                         1
public commute helper app                                   1
mutual fund investing platform                              1
it                                                          1
automated storage & warehousing solution                    1
document digitization platform                              1
virtual reality, 3d simulation and stereoscopic products    1
kids tool kit for innovation platform                       1
transportation                                              1
spam call block app                                         1
tech enabled ac bus service                                 1
cross-channel crm platform                                  1
coupon aggregator platform                                  1
prepaid bill manager app                                    1
non profit organization to alleviate poverty                1
location based app                                          1
budget accommodation aggregator                             1
holiday resort chain                                        1
location based engagement & rewards platform                1
fund raising platform for startups                          1
architectural design & consulting                           1
Name: sort_ind_vert, Length: 166, dtype: int64

In [204]:
#testing 'key word' for sorting data
i = ['data','analytics']
sfin['sort_ind_vert'].loc[sfin['sort_ind_vert'].str.contains('apparel',regex=True)]

Series([], Name: sort_ind_vert, dtype: object)

In [205]:
sfin.head(100)

,Startup Name,SubVertical,City Location,Investors Name,InvestmentnType,date,amount,invst_type_sorted,Sorted_Cities,industry_vertical,sort_ind_vert
0,BYJU’S,e-learning,Bengaluru,Tiger Global Management,private equity round,2020-09-01,2.000000e+08,private_angel,Bengaluru_area,e-tech,edtech_industry
1,Shuttl,app based shuttle service,Gurgaon,Susquehanna Growth Equity,series c,2020-01-13,8.048394e+06,series_C_H,Delhi_NCR,transportation,transport_industry
2,Mamaearth,retailer of baby and toddler products,Bengaluru,Sequoia Capital India,series b,2020-09-01,1.835886e+07,pre_series_A_B,Bengaluru_area,e-commerce,lifestyle_services
3,https://www.wealthbucket.in/,online investment,New Delhi,Vinod Khatumal,pre-series a,2020-02-01,3.000000e+06,pre_series_A_B,Delhi_NCR,fintech,fintech_services
4,Fashor,embroiled clothes for women,Mumbai,Sprout Venture Partners,seed round,2020-02-01,1.800000e+06,private_angel,Mumbai_area,fashion and apparel,lifestyle_services
5,Pando,"open-market, freight management platform",Chennai,Chiratae Ventures,series a,2020-01-13,9.000000e+06,pre_series_A_B,Chennai_area,logistics,logistics_industry
6,Zomato,online food delivery platform,Gurgaon,Ant Financial,private equity round,2020-10-01,1.500000e+08,private_angel,Delhi_NCR,hospitality,food_beverages_industry
7,Ecozen,agritech,Pune,Sathguru Catalyzer Advisors,series a,2019-12-12,6.000000e+06,pre_series_A_B,Pune_area,technology,agritech_industry
8,CarDekho,automobile,Gurgaon,Ping An Global Voyager Fund,series d,2019-06-12,7.000000e+07,series_C_H,Delhi_NCR,e-commerce,transport_industry
9,Dhruva Space,satellite communication,Bengaluru,"Mumbai Angels, Ravikanth Reddy",seed,2019-03-12,5.000000e+07,private_angel,Bengaluru_area,aerospace,aerospace
10,Rivigo,logistics services and solutions,Gurgaon,"SAIF Partners, Spring Canter Investment Ltd.",series f,2019-12-13,2.000000e+07,series_C_H,Delhi_NCR,technology,logistics_industry
11,Healthians,food solutions for corporate,Bengaluru,"Paytm, NPTK, Sabre Partners and Neoplux",series c,2019-12-17,1.200000e+07,series_C_H,Bengaluru_area,b2b-focused foodtech startup,food_beverages_industry
12,Licious,online meat and seafood ordering startup,Bengaluru,Vertex Growth Fund,series e,2019-12-16,3.000000e+07,series_C_H,Bengaluru_area,e-commerce,food_beverages_industry
13,InCred,non-banking financial company,Mumbai,Undisclosed Investors,debt funding,2019-12-16,5.900000e+06,debt_fund,Mumbai_area,finance,fintech_services
14,Trell,experience discovery platform,Bengaluru,Ruizheng Investment,seed round,2019-12-14,2.000000e+06,private_angel,Bengaluru_area,video,lifestyle_services
15,Rein Games,real money based gaming startup,Noida,Manipal Education and Medical Group (MEMG),seed round,2019-11-12,5.000000e+07,private_angel,Delhi_NCR,gaming,media_entertainment_services
16,Lenskart.com,online eyewear shopping portal,Faridabad,SoftBank Vision Fund,series g,2019-12-20,2.310000e+08,series_C_H,Delhi_NCR,e-commerce,online_and_booking_services
17,Freshworks,business and customer engagement tools,San Francisco,"Sequoia, CapitalG, Accel",series h,2019-11-13,1.500000e+08,series_C_H,Others,software,software_cloud_services
18,Misters,men's health and wellness brand,Gurgaon,"Sauce.vc, Rainforest Ventures",series b,2019-11-14,4.860000e+05,pre_series_A_B,Delhi_NCR,health and wellness,meditech_industry
19,Sunstone Eduversity Pvt. Ltd,elearning,Gurgaon,"Prime Venture Partners, LetsVenture, PS1 Venture and GlobalLogic co-founder Rajul Garg",seed,2019-11-13,1.500000e+06,private_angel,Delhi_NCR,education,edtech_industry
20,Burger Singh,indian burger brand,Gurgaon,RB Investments,venture,2019-11-17,NaN,venture_capital,Delhi_NCR,food and beverage,food_beverages_industry
21,Healthians,healthcare services,Gurgaon,"DG Daiwa Ventures, DG Incubation",series b,2019-11-18,1.200000e+07,pre_series_A_B,Delhi_NCR,health and wellness,meditech_industry
22,Ninjacart,agritech,Bengaluru,Trifecta Capital Advisors,debt funding,2019-11-15,2.600000e+07,debt_fund,Bengaluru_area,b2b marketing,agritech_industry
23,Aye Finance,financial services to msmes,Gurgaon,FinTech,debt funding,2019-11-20,1.741126e+07,debt_fund,Delhi_NCR,fintech,fintech_services
24,SuperGaming,social gaming platform,Pune,Dream Incubator,seed funding,2019-12-11,1.300000e+06,private_angel,Pune_area,video games,media_entertainment_services
25,Clumio,recovery software,"San Jose,","Altimeter Capital, Sutter Hill Ventures",series c,2019-11-20,1.350000e+08,series_C_H,Others,saas,software_cloud_services
26,eBikeGo,electric bike rental,Amritsar,Startup Buddy,seed,2019-11-11,3.000000e+05,private_angel,Others,last mile transportation,transport_industry
27,Digital Mall Asia,virtual e-commerce platform,Delhi,Amour Infrastructure,seed funding,2019-11-19,2.200000e+08,private_angel,Delhi_NCR,e-commerce,ecommerce_industry
28,Medikabazaar,b2b platform for medical supplies,Mumbai,"Ackermans & van Haaren, HealthQuad, Rebright Partners, Toppan Printing",series b,2019-11-18,1.580000e+07,pre_series_A_B,Mumbai_area,healthcare,meditech_industry
29,Vogo Automotive,scooter sharing app,Kormangala,"Matrix Partners, Stellaris Venture Partners, Kalaari Capital",series b,2019-11-15,2.830000e+08,pre_series_A_B,Bengaluru_area,last mile transportation,transport_industry
...,...,...,...,...,...,...,...,...,...,...,...
70,Indus OS,smartphone operating system,Andheri,Ventureast,series b,2019-10-07,5.750000e+06,pre_series_A_B,Mumbai_area,tech,tech
71,HealthAssure,primary care medical network,Mumbai,Blume Ventures,series a,2019-10-07,2.500000e+06,pre_series_A_B,Mumbai_area,health care,meditech_industry
72,House of Msasaba,clothes and apparel,Mumbai,Binny Bansal,series a,2019-09-07,1.000000e+06,pre_series_A_B,Mumbai_area,luxury label,luxury label
73,Board Infinity,full-stack career platform,Chembur,Multiple Angel Investors,angel round,2019-08-07,3.196050e+05,private_angel,Mumbai_area,edtech,lifestyle_services
74,NoBroker,real estate,Bengaluru,General Atlantic,series c,2019-05-06,5.100000e+07,series_C_H,Bengaluru_area,e-commerce,real_estate_services
75,Bira91,brewery,New Delhi,Anicut Capital,debt funding,2019-04-06,1.000000e+07,debt_fund,Delhi_NCR,food and beverage,food_beverages_industry
76,FabHotels,hospitality,Gurgaon,"Goldman Sachs, Accel Partners and Qualcomm",NaN,2019-03-06,4.889976e+06,other_funding,Delhi_NCR,e-commerce,ecommerce_industry
77,Avail Finance,fintech,Bengaluru,Matrix Partners,series a,2019-03-06,9.000000e+06,pre_series_A_B,Bengaluru_area,finance,fintech_services
78,BharatPe,fintech,New Delhi,Insight Partners,series b,2019-04-06,7.500000e+07,pre_series_A_B,Delhi_NCR,finance,fintech_services
79,Recykal,optimization,Hyderabad,"Triton Investment Advisors, Pidilite Industries director Ajay Parekh",pre-series a,2019-04-06,2.600000e+07,pre_series_A_B,Hyderabad_area,waste management service,waste management service
80,Agara Labs,artificial intelligence,Bengaluru,Blume Ventures and RTP Global,pre-series a,2019-03-06,2.500000e+06,pre_series_A_B,Bengaluru_area,deep-tech,AI_Data_analytics_services
81,Sistema.bio,hybrid reactor biodigestor,Nairobi,"Shell Foundation, DILA CAPITAL, Engie RDE Fund, EcoEnterprise Fund, EDFIMC (ElectriFI), Endeavor Catalyst Fund, CoCapital, Triodos, Alpha Mundi, and Lendahand",NaN,2019-06-06,2.739035e+06,other_funding,Others,agriculture,agriculture
82,Chakr Innovation,renewable energy,New Delhi,IAN Fund,series a,2019-06-06,2.600000e+07,pre_series_A_B,Delhi_NCR,energy,energy_industry
83,Pratilipi,e-books,Bengaluru,Qiming Venture Partners,series b,2019-06-06,1.510950e+07,pre_series_A_B,Bengaluru_area,digital media,digital media
84,Bolo App,video platform,Bengaluru,Nexus Venture Partners,seed funding,2019-10-06,4.302000e+05,private_angel,Bengaluru_area,digital media,media_entertainment_services
85,OkCredit,financial services,Haryana,Tiger Global Management,series a,2019-10-06,1.550000e+07,pre_series_A_B,Others,fintech,fintech_services
86,Biz2Credit,online lending platform,New York,WestBridge Capital,series b,2019-06-06,5.200000e+07,pre_series_A_B,Others,fintech,fintech_services
87,Vogo Automotive Pvt. Ltd.,dockless scooter rental company,Karnataka,Alteria Capital,debt funding,2019-08-06,3.584000e+06,debt_fund,Others,transportation,transport_industry
88,Leegality,digital documentation,Mumbai/Bengaluru,Mumbai Angels,series a,2019-04-06,3.400000e+06,pre_series_A_B,Others,services,services
89,Ola Electric,cabs,Bengaluru,Tata Sons,series a,2019-06-05,NaN,pre_series_A_B,Bengaluru_area,transport,transport_industry
90,Saahas Zero Waste,optimization,Bengaluru,C4D Partners,venture - series unknown,2019-06-05,8.686000e+05,venture_capital,Bengaluru_area,waste management service,waste management service
91,StyleDotMe,fashion and shopping,Delhi,"Indian Angel Network and other angel investors, Innov8 founder Ritesh Malik, Josh Talks founders Supriya Paul and Shobha Banga, and former Hero Corporate president Rohit Chanana",bridge round,2019-05-05,NaN,other_funding,Delhi_NCR,e-commerce,lifestyle_services
92,BlackBuck,logistics,Bengaluru,"Goldman Sachs Investment Partners and Silicon Valley-based Accel, Wellington, Sequoia Capital, B Capital, LightStreet, Sands Capital and International Finance Corporation,",series d,2019-01-05,1.500000e+08,series_C_H,Bengaluru_area,transport,logistics_industry
93,Zenoti,beauty and wellness industry,Hyderabad,Tiger Global Management,series c,2019-02-05,5.000000e+07,series_C_H,Hyderabad_area,saas,lifestyle_services
94,Ather Energy,electric vehicle,Bengaluru,Sachin Bansal,series c,2019-05-28,5.100000e+07,series_C_H,Bengaluru_area,automobile,transport_industry
95,FreshVnF,fresh agriculture produces,Mumbai,Equanimity Ventures,seed round,2019-05-28,1.400000e+08,private_angel,Mumbai_area,agtech,agritech_industry
96,GlowRoad,retail,Bengaluru,"Korea Investment Partners, Vertex Ventures",series b,2019-05-30,1.150000e+07,pre_series_A_B,Bengaluru_area,e-commerce,ecommerce_industry
97,Bira91,brewery,New Delhi,Sixth Sense Ventures,series b,2019-05-31,5.600000e+06,pre_series_A_B,Delhi_NCR,food and beverage,food_beverages_industry
98,Kuvera,wealth management,Bengaluru,Eight Roads,series a,2019-04-16,4.500000e+07,pre_series_A_B,Bengaluru_area,finance,fintech_services
99,Medlife,online medicine,Bengaluru,Prasid Uno Family Trust,private equity,2019-12-04,1.700000e+07,private_angel,Bengaluru_area,e-commerce,meditech_industry

In [206]:
# Final converttion unstorable data to 'Unsorted services'
for x in sfin['sort_ind_vert']:
    if x in top_services:
        sfin['sort_ind_vert'] = sfin['sort_ind_vert']
    else:
        sfin['sort_ind_vert'] = sfin['sort_ind_vert'].replace(to_replace=x, value='unsorted_services')

In [208]:
sfin.head()

,Startup Name,SubVertical,City Location,Investors Name,InvestmentnType,date,amount,invst_type_sorted,Sorted_Cities,industry_vertical,sort_ind_vert
0,BYJU’S,e-learning,Bengaluru,Tiger Global Management,private equity round,2020-09-01,200000000.0,private_angel,Bengaluru_area,e-tech,edtech_industry
1,Shuttl,app based shuttle service,Gurgaon,Susquehanna Growth Equity,series c,2020-01-13,8048394.0,series_C_H,Delhi_NCR,transportation,transport_industry
2,Mamaearth,retailer of baby and toddler products,Bengaluru,Sequoia Capital India,series b,2020-09-01,18358860.0,pre_series_A_B,Bengaluru_area,e-commerce,lifestyle_services
3,https://www.wealthbucket.in/,online investment,New Delhi,Vinod Khatumal,pre-series a,2020-02-01,3000000.0,pre_series_A_B,Delhi_NCR,fintech,fintech_services
4,Fashor,embroiled clothes for women,Mumbai,Sprout Venture Partners,seed round,2020-02-01,1800000.0,private_angel,Mumbai_area,fashion and apparel,lifestyle_services

In [209]:
sfin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 11 columns):
Startup Name         3044 non-null object
SubVertical          3044 non-null object
City  Location       3044 non-null object
Investors Name       3044 non-null object
InvestmentnType      3040 non-null object
date                 3044 non-null datetime64[ns]
amount               2065 non-null float64
invst_type_sorted    3044 non-null object
Sorted_Cities        3044 non-null object
industry_vertical    3044 non-null object
sort_ind_vert        3044 non-null object
dtypes: datetime64[ns](1), float64(1), object(9)
memory usage: 261.7+ KB

In [211]:
sfin['sort_ind_vert'].value_counts()

unsorted_services               418
online_and_booking_services     346
fintech_services                278
lifestyle_services              234
meditech_industry               224
marketplace_services            205
unclassified                    171
food_beverages_industry         153
edtech_industry                 140
ecommerce_industry              123
media_entertainment_services    121
transport_industry              119
software_cloud_services         108
AI_Data_analytics_services      108
logistics_industry              92
hyperlocal_services             62
travel_industry                 58
real_estate_services            30
b2b_services                    21
agritech_industry               17
energy_industry                 16
Name: sort_ind_vert, dtype: int64

In [210]:
sfin.describe()

             amount
count  2.065000e+03
mean   1.842990e+07
std    1.213734e+08
min    1.600000e+04
25%    4.700000e+05
50%    1.700000e+06
75%    8.000000e+06
max    3.900000e+09

In [212]:
sfin.to_excel("Startup_information_cleaned.xlsx",sheet_name='cleaned_sorted')

In [781]:
#sfin.close()